### ISSUE TITLE
If the added line is the last line in a zone, it is sometimes omitted in the output

### ISSUE THREAD

**Issue by brobertson** [brobertson/Lace2#105]

**Comment by brobertson** [comment]
Split from #102

**Comment by brobertson** [comment]
@mkonieczny9805, do we have examples of this?

**Comment by mkonieczny9805** [comment]
@brobertson Yes, it happened on at least one page in the Aelius Herodianus text I recently edited (Grammatici Graeci 3.1), but that's been taken down from Lace now so I can't provide a link. I've got the backup .xar file so conceivably we could find it.
