### ISSUE TITLE
Funk Xar installation troubles

### ISSUE THREAD

**Issue by duncdrum** [brobertson/Lace2#127]
When navigating to the `Funk, F. X.` text on trylace.org the `Download XAR files` package contains an unresolvable dependency:
```xml
 <pkg:dependency package="http://heml.mta.ca/Lace/Images/didascaliaetcons00funk"/>
```
Consequently, it fails to install into another instance running lace. Either the info text needs tweaking, or the generation of the `xar` needs to be adjusted. Not sure which it is.

**Comment by brobertson** [comment]
Every text package has a corresponding image package on which it is dependent. I've put it up here:
https://drive.google.com/file/d/1XwiVui2x3xrMS0gdowvtCacttyyr9LET/view?usp=sharing

Your experiment illustrates the problem I was trying to solve by changing the repo.: it pointed to a repo that has all the image packages, so a manual installation of a text package like this would work. Your multi-repo. patch will solve this.
