### ISSUE TITLE
buggy behaviour of 'verify whole line'

### ISSUE THREAD

**Issue by mromanello** [brobertson/Lace2#130]
Hello 👋

We noticed a bug-like behaviour of the 'verify whole line' function in Lace2 (Using chrome Version 87.0.4280.88 (Official Build) (x86_64)). When clicking on it after a correction, the line is marked in light blue but after browser refresh the corrections made are gone. Attached you find a short video illustrating the problem. All works well, though, when pressing enter on each corrected word.

https://user-images.githubusercontent.com/310693/105327897-c405bb80-5bcf-11eb-8222-4418ebde7184.mov

**Comment by brobertson** [comment]
This is behaviour that I expect, but that you (reasonably) did not. Every changed word needs to be entered into the database by hitting return and thereby making it blue. 'Verify whole line' takes any word that hasn't been corrected by this method and verifies it, or takes its original form and says that it's the right one.

I need to think about how to articulate this better: I'll open an enhancement issue that points to this helpful video.
