### ISSUE TITLE
Lace export refinement

### ISSUE THREAD

**Issue by lcerrato** [brobertson/Lace2#139]
I don't see an `<editor>` tag following the title and author. It will be easy for me to omit/miss that.

Also a space before and after the `<pb/>` would be appreciated.

**Comment by brobertson** [comment]
Hi, Lisa. I think these are refinements that are best done in a project-specific XSLT script applied to Lace's output. Let's make a list of the things you like/want in a pretty-printed XML file for OGL and I can work on XSLT for that.

**Comment by lcerrato** [comment]
@brobertson 
Thanks. I already check them manually.
I don't need XSLT at this point as I prefer to read through this work. 
I am just trying to reduce inadvertent omissions.
