### ISSUE TITLE
some exports dropping capital letters

### ISSUE THREAD

**Issue by lcerrato** [brobertson/Lace2#141]
Just a heads up —
I've spotted a few recent texts where the initial capital letter is missing from a word. 
This may be isolated to specific circumstances such as the texts I'm working on, but I've seen it in two different volumes this week.

**Comment by brobertson** [comment]
Hi, Lisa. Thanks! If you could append some xml here with the guilty texts, that would be great. Is it possible that these have been run through a script that removes Latin-script letters? In that case, errant capital-e in place of capital-epsilon would get stripped.

**Comment by lcerrato** [comment]
I forget which one it was yesterday because I wasn't tracking it but I saw it in
urn:cts:greekLit:tlg4026.tlg003.1st1K-grc1 today

(It's possible tidy cleaned it up but these were capital pi and delta so not the type of letters that would be confused.)

I wasn't tracking it carefully (I will from now on), but here is one passage
`[a 16] εῖ δὲ παρὰ ταῦτα μηδένα ἄλλον τρόπον ἐρωτήσεων τῶν`
https://archive.org/details/commentariaina21pt12akaduoft/page/331/mode/1up?view=theater

**Comment by lcerrato** [comment]
In tlg0557.tlg004.1st1K-grc1 missing Π
```
<div type="textpart" subtype="section" xml:base="urn:cts:greekLit:tlg0557.tlg004.1st1K-grc1" n="2">
        <p rend="indent">2.  αρὰ
```

**Comment by brobertson** [comment]
Phew. So unlikely to be a Lace problem, but if you can append the original file here, I can check if my MacOS tidy makes this error. We should file a bug against tidy for sure. However, in the long run, we can use XSLT to do all your postprocessing, including indenting and that should be more reliable.

**Comment by brobertson** [comment]
I'll leave this open until we're certain it's not a Lace issue.

**Comment by brobertson** [comment]
Ok, I freshly generated urn:cts:greekLit:tlg0557.tlg004.1st1K-grc1 and the uppercase pi is still there. I processed the file with Linux parallel tidy -xml -m -i {} ::: *xml and the result also has the uppercase pi.

**Comment by lcerrato** [comment]
This was a recent batch
[ldpd_10922736_000.zip](https://github.com/brobertson/Lace2/files/6319583/ldpd_10922736_000.zip)

**Comment by brobertson** [comment]
Hi, Lisa. ldpd_10922736_000.zip is the set of files I based my comments above. When I generated them at heml.mta.ca/lace I did not see these problems in the Lace output, but rather post tidy (in macos).

**Comment by brobertson** [comment]
As for the initial example, I find that the Δ is missing in the editing, as shown in this image
![Screenshot from 2021-04-15 13-59-38](https://user-images.githubusercontent.com/34581/114908828-dd935980-9df2-11eb-952a-d3b7ab3dca05.png)

**Comment by brobertson** [comment]
I've asked Charlotte to do a last scan of commentariaina21pt12akaduoft as up at heml.mta.ca/lace

**Comment by lcerrato** [comment]
@brobertson 
Yes, I agree on this. I just could not be sure in the middle of the workflow (have to go back and redownload and compare, etc.). Some of these were near those Aristotle brackets so I thought that could have been creating some noise at first.

**Comment by brobertson** [comment]
Issue resolved because it was not caused by Lace, but either by erroneous editing or post-processing in MacOS 'tidy'.
